project_id = "pbqpbupsmzafbzlxccov"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[graphql]
enabled = true
port = 54329
pool_size = 20
max_rows = 1000

[db]
enabled = true
port = 54322
major_version = 15

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54329
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.telegram-webhook]
verify_jwt = false

[functions.send-verification]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.telegram-auth]
verify_jwt = false

[functions.forward-swap-request]
verify_jwt = false

[functions.match-notification-webhook]
verify_jwt = false

[functions.match-drop-requests]
verify_jwt = false