// Shared course list used across the application
export const COURSE_LIST = [
  "هندسة البرمجيات",
  "تمثيل واستدلال المعرفة",
  "التنقيب عن البيانات",
  "الذكاء الاصطناعي",
  "الأنطولوجيا ومخططات المعرفة",
  "الأنظمة المضمنة",
  "معالجة اللغات الطبيعية",
  "الروبوتات الذكية",
  "الاعداد الوظيفي 1 (مشروع)",
  "أمن وخصوصية المعلومات",
  "برمجة الذكاء الاصطناعي",
  "التعلم الآلي والشبكات العصبونية",
  "التعلم العميق",
  "رياضيات منفصلة", 
  "تراكيب البيانات",
  "برمجة الكائنات الموجهة",
  "أنظمة إدارة قواعد البيانات",
  "ندوة - الطريق إلى صناعة البرمجيات",
  "أساسيات تكنولوجيا المعلومات",
  "تطوير تطبيقات الويب",
  "الجبر الخطي لعلوم الحوسبة",
  "الريادة والابتكار في تكنولوجيا المعلومات",
  "موضوعات خاصة في الذكاء الاصطناعي",
  "الإحصاء التطبيقي",
  "قواعد البيانات غير العلائقية",
  "البيانات الضخمة",
  "العلوم العسكرية",
  "الثقافة الوطنية",
  "مقدمة في الفلسفة والتفكير الناقد",
  "المهارات الحياتية والعملية",
  "الأخلاق والقيم الإنسانية",
  "الريادة والإبتكار",
  "الإسلام وقضايا العصر",
  "الحضارة العربية الاسلامية",
  "الاردن تاريخ وحضارة",
  "القدس",
  "الثقافة البيئية والتنمية",
  "الثقافة الإسلامية",
  "الثقافة القانونية",
  "الثقافة البدنية",
  "التجارة الإلكترونية",
  "وسائل التواصل الاجتماعي",
  "تذوق الفنون",
  "اللغة الأجنبية"
];

// Course translations (for potential future use)
export const COURSE_TRANSLATIONS: { [key: string]: string } = {
  "Calculus I": "Calculus I",
  "Calculus II": "Calculus II", 
  "Linear Algebra": "Linear Algebra",
  "Physics": "Physics",
  "Chemistry": "Chemistry",
  "Biology": "Biology",
  "Computer Science": "Computer Science",
  "Economics": "Economics",
  "Psychology": "Psychology",
  "Introduction to Programming": "Introduction to Programming",
  "Data Structures": "Data Structures",
  "Database Systems": "Database Systems",
  "Artificial Intelligence": "Artificial Intelligence",
  "Software Engineering": "Software Engineering",
  "Web Development": "Web Development",
  "Statistics": "Statistics",
  "Marketing": "Marketing",
  "Finance": "Finance",
  "Accounting": "Accounting",
  "Management": "Management",
  "English Literature": "English Literature",
  "Arabic Literature": "Arabic Literature",
  "History": "History",
  "Geography": "Geography",
  "Political Science": "Political Science",
  "Sociology": "Sociology",
  "other": "Other"
};