// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbqpbupsmzafbzlxccov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBicXBidXBzbXphZmJ6bHhjY292Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4ODA3MjcsImV4cCI6MjA2MjQ1NjcyN30.14wg8bj756NrgxX-CvpW1NLYU5Z9m3S7_yaTbZ4KJAU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);